### YamlMime:Sample
uid: XfTestRepo.get-started-advanced-configuration.1-accessing-advanced-settings 
metadata: 
  name: Accessing advanced settings 
  description: Accessing advanced settings description
  languages:
    - c#
    - .net
  products:
    - products1
    - products2  
name: name1
authors: 
  - displayName: author1
    id: 1
  - displayName: author2
    id: 2
languages:
  - c#
  - .net
products:
  - products1
  - products2  
description: test description

