### YamlMime:Sample
uid: XfTestRepo.get-started-advanced-configuration.1-accessing-advanced-settings 
metadata: 
  title: Accessing advanced settings 
  description: Accessing advanced settings 
  author: dbeasley 
azureDeployPath: Microsoft.Sample
authors: 
  - displayName: author1
    id: 1
  - displayName: author2
    id: 2
codeUrl: https://www.baidu.com
description:  | 
  [!include[](description.md)] 
languages:
  - en-us
name: test name
# summary: (.md)
products:
  - products1
  - products2
zipUrl: https://github.com
