### YamlMime:Sample
uid: XfTestRepo.get-started-advanced-configuration.1-accessing-advanced-settings 
metadata: 
  title: Accessing advanced settings 
  description: Accessing advanced settings 
  authors: 
    - displayName: author1
      id: 1
    - displayName: author2
      id: 2
  codeUrl: https://www.bing.com
  zipUrl: https://github.com
  languages:
    - c#
    - .net
  products:
    - products1
    - products2
  azureDeployPath: Microsoft.Sample
  name: name1
  des: des1

