### YamlMime:Sample
uid: XfTestRepo.get-started-advanced-configuration.1-accessing-advanced-settings 
metadata: 
  test_name: Accessing advanced settings 
  test_description: Accessing advanced settings description
name: name1
authors: 
  - displayName: author1
    id: 1
  - displayName: author2
    id: 2
languages:
  - c#
  - .net
products:
  - products1
  - products2  
description: test description

