### YamlMime:Sample
uid: XfTestRepo.get-started-advanced-configuration.1-accessing-advanced-settings 
metadata: 
  _name: Accessing advanced settings 
  _description: Accessing advanced settings 
  _authors: 
    - displayName: author1
      id: 1
    - displayName: author2
      id: 2
  codeUrl: https://www.bing.com
  zipUrl: https://github.com
  _languages:
    - c#
    - .net
  _products:
    - products1
    - products2
  azureDeployPath: Microsoft.Sample
name: name1
authors: 
  - displayName: author1
    id: 1
  - displayName: author2
    id: 2
languages:
  - c#
  - .net
products:
  - products1
  - products2  

